name: 'Refinery-RS Framework'
description: 'All-in-one Rust compilation framework 🦀🏭'

inputs:
  binary_name:
    description: 'The name of your project binary'
    required: true
    default: 'refinery'

runs:
  using: "composite"
  steps:
    - name: Build for Linux 🐧
      if: runner.os == 'Linux'
      uses: sircesarium/refinery-rs/components/build/linux@main
      with:
        binary_name: ${{ inputs.binary_name }}

    - name: Build for Windows 🪟
      if: runner.os == 'Windows'
      uses: sircesarium/refinery-rs/components/build/windows@main
      with:
        binary_name: ${{ inputs.binary_name }}

    - name: Build for macOS 🍎
      if: runner.os == 'macOS'
      uses: sircesarium/refinery-rs/components/build/mac@main
      with:
        binary_name: ${{ inputs.binary_name }}