name: "Refinery-RS Framework"
description: "All-in-one Rust compilation framework 🦀🏭"

inputs:
  binary_name:
    description: "The name of your project binary"
    required: true
  features:
    description: "Space separated list of features to enable"
    required: false
    default: ""
  github_token:
    description: "Token to upload to release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build for Linux 🐧
      if: runner.os == 'Linux'
      uses: sircesarium/refinery-rs/components/build/linux@main
      with:
        binary_name: ${{ inputs.binary_name }}
        features: ${{ inputs.features }}

    - name: Build for Windows 🪟
      if: runner.os == 'Windows'
      uses: sircesarium/refinery-rs/components/build/windows@main
      with:
        binary_name: ${{ inputs.binary_name }}
        features: ${{ inputs.features }}

    - name: Build for macOS 🍎
      if: runner.os == 'macOS'
      uses: sircesarium/refinery-rs/components/build/mac@main
      with:
        binary_name: ${{ inputs.binary_name }}
        features: ${{ inputs.features }}

    - name: Auto-Release 🏷️
      shell: bash
      run: |
        gh release create ${{ github.ref_name }} output/* --target ${{ github.sha }} --yes --clobber
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
