name: "Refinery-RS Linux Library Builder"
description: "Builds and exports Linux shared objects and static archives"
inputs:
  binary_name:
    description: "The name of the library to build"
    required: true
  target:
    description: "The Rust target triple for the compilation"
    required: true
  output_dir:
    description: "Directory where the libraries will be stored"
    default: "output"
  linux_32bit:
    description: "Enable i686-unknown-linux-musl target"
    default: "false"
  linux_arm64:
    description: "Enable aarch64-unknown-linux-musl target"
    default: "false"
  linux_armv7:
    description: "Enable armv7-unknown-linux-musleabihf target"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Install Cross
      shell: bash
      run: cargo install cross --git https://github.com/cross-rs/cross.git

    - name: Build Multi-Arch Libraries
      shell: bash
      run: |
        export CROSS_RUSTFLAGS="-C target-feature=-crt-static"
        
        TARGETS=("x86_64-unknown-linux-musl")
        if [ "${{ inputs.linux_32bit }}" == "true" ]; then TARGETS+=("i686-unknown-linux-musl"); fi
        if [ "${{ inputs.linux_arm64 }}" == "true" ]; then TARGETS+=("aarch64-unknown-linux-musl"); fi
        if [ "${{ inputs.linux_armv7 }}" == "true" ]; then TARGETS+=("armv7-unknown-linux-musleabihf"); fi

        for TARGET in "${TARGETS[@]}"; do
          cross build --release --target $TARGET

          LIB_DIR="${{ inputs.output_dir }}/lib/$TARGET"
          mkdir -p "$LIB_DIR"
          
          cp "target/$TARGET/release/lib${{ inputs.binary_name }}.so" "$LIB_DIR/lib${{ inputs.binary_name }}-$TARGET.so" || true
          cp "target/$TARGET/release/lib${{ inputs.binary_name }}.a" "$LIB_DIR/lib${{ inputs.binary_name }}-$TARGET.a" || true
        done
